---
version: '3.8'

services:
 jenkins:
  image: jenkins
  ports:
   - 5050:8080
  deploy:
   replicas: 2
   placement:              
    constraints:
     - node.hostname == Manager

 qaserver:
  image: tomcat
  ports:
   - 6060:8080
  deploy:
   replicas: 3
   placement:
    constraints:
     - node.hostname == Worker1
 prodsserver:
  image: tomcat
  ports:
   - 7070:8080
  deploy:
   replicas: 4
   placement:
    constraints:
     - node.hostname == Worker2
...
 
